### ISSUE TITLE
Cannot switch compatLevel in configuration

### ISSUE THREAD

**Issue by ErikZigo** [keboola/generic-extractor#86]
Testovaci mock:
http://www.mocky.io/v2/59bfde2c1100001302fa036b

Testovaci konfigurace:
```
{
  "parameters": {
    "api": {
      "baseUrl": "http://www.mocky.io/v2/59bfde2c1100001302fa036b"
    },
    "config": {
      "debug": true,
      "jobs": [
        {
          "endpoint": "/v2/59bfde2c1100001302fa036b",
          "dataField": "rows",
          "dataType": "rows"
        }
      ]
    }
  }
}
```

API vraci v `rows` pro kazdy zaznam vnorene pole hodnot.

Generic 2 a 3 si s tim poradi. Zaloguje warning o `Converting nested array to JSON string` a ulozi data do jednoho sloupce.

Problem nastava kdyz Generic 3 spousti stare konfigurace (2), ktere maji ulozeny auto mapping json parseru ve `state` konfigurace.

To konci spusteni chybou `Error parsing response JSON: Unsupported data row`.
Zkousel jsem do sekce config pridat `"compactLevel": 2`, ale bez vysledku. Failuje to stejne.

**Comment by ErikZigo** [comment]
Bylo by fajn, kdyby generic logoval i jaky `compactLevel` je pouzity.

**Comment by odinuv** [comment]
fixed in https://github.com/keboola/juicer/commit/463528d0cabbd131da6cc08f4967f89f70f20e51
chybelo tam nastaveni konverze - kdyz to ma stary state, tak se to neda tim compatLevel zvednout (protoze by ten state nesel precist), do logu to pise neco jako legacy parser because it is in state.
Vysledek to vraci stejny, takze resenim je i uplne smazani statu, nicmene ted uz to bude funovat v kazdym pripade.
